version: '3'
services:

  db:
    image: "postgres:12-alpine"
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mongo:
    image: "mongo"
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
  api:
    image: "alexandre3gomes/finances-easy-api"
    container_name: api
    ports:
      - 8089:8089
    depends_on:
      - db
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/finances
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
  chat:
    image: "alexandre3gomes/chat-service"
    container_name: chat
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb+srv://finances:finances@cluster0.1n7zl.mongodb.net/chat?retryWrites=true&w=majority
  web:
    image: "alexandre3gomes/finances-easy-web"
    container_name: web
    ports:
      - 8080:8080
    depends_on:
      - api

volumes:
  postgres_data:
  mongo_data: