version: '3'
services:

  db:
    image: "postgres:12-alpine"
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/finances
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
  api:
    image: "alexandre3gomes/finances-easy-api"
    container_name: api
    ports:
      - 8089:8089
    depends_on:
      - db

  web:
    image: "alexandre3gomes/finances-easy-web"
    container_name: web
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  postgres_data: