server:
  port: 8089
  ssl:
    key-store-type: PKCS12
    enabled: false
    key-store: classpath:cert/finances-easy_com.p12
    key-store-password: 123456
    key-store-alias: finances-easy
spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/finances}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.format_sql: true
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"