server:
  port: 8089
spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/finances}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.format_sql: false
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${OKTA_CLIENT_ID}
            client-secret: ${OKTA_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          okta:
            issuer-uri: https://dev-2225315.okta.com/oauth2/default
      resourceserver:
        jwt:
          issuer-uri: https://dev-2225315.okta.com/oauth2/default
management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  swagger-ui:
    path: /public/swagger-ui.html
