package net.finance.entity;
// Generated 02/05/2018 18:17:54 by Hibernate Tools 5.2.8.Final

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Developers generated by hbm2java
 */
@Entity
@Table(name = "USER")
@Data
@NoArgsConstructor
public class User implements Serializable, UserDetails {

	/**
	 *
	 */
	private static final long serialVersionUID = -6578425493164749786L;
	@Id @GeneratedValue(strategy = GenerationType.IDENTITY) @Column(name = "ID_USER", unique = true, nullable = false, precision = 3, scale = 0) private Integer id;
	@Column(name = "NAME", nullable = false, length = 40) private String name;
	@Column(name = "USERNAME", nullable = true, length = 50) private String username;
	@Column(name = "PASSWORD", nullable = true, length = 100) private String password;

	@JsonIgnore
	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
		return new ArrayList<>();
	}

	@JsonIgnore
	@Override
	public boolean isAccountNonExpired() {
		return true;
	}

	@JsonIgnore
	@Override
	public boolean isAccountNonLocked() {
		return true;
	}

	@JsonIgnore
	@Override
	public boolean isCredentialsNonExpired() {
		return true;
	}

	@JsonIgnore
	@Override
	public boolean isEnabled() {
		return true;
	}
}
