version: '3'
services:

  db:
    image: "postgres:12-alpine"
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
  api:
    image: "alexandre3gomes/finances-easy-api"
    container_name: api
    ports:
      - 8089:8089
    depends_on:
      - db
    environment:
      - POSTGRES_URL=jdbc:postgresql://db:5432/finances
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
  web:
    image: "alexandre3gomes/finances-easy-web"
    container_name: web
    ports:
      - 8080:8080
    depends_on:
      - api
  prometheus:
    image: alexandre3gomes/prometheus
    container_name: prometheus
    ports:
      - 9000:9090
    volumes:
      - prometheus_data:/prometheus

volumes:
  postgres_data:
  mongo_data:
  prometheus_data: