name: Build app
on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'
          architecture: x64
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run gradle build image
        run: ./gradlew bootBuildImage --imageName=rg.fr-par.scw.cloud/alexandre3gomes/finances-easy
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/alexandre3gome
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            rg.fr-par.scw.cloud/alexandre3gomes/finances-easy