name: Build Jar
on:
  push:
    branches:
      - dev

jobs:
  build-jar:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          architecture: x64
      - name: Build gradle
        run: ./gradlew bootJar
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: build/libs/finances-easy-api-1.0.0.jar
      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: jar
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: finances-easy-api
          environment_name: finances-easy-api
          version_label:  ${{ steps.buildnumber.outputs.build_number }}
          region: eu-west-1
          deployment_package: finances-easy-api-1.0.0.jar
