name: Deploy app
on:
  workflow_run:
    workflows:
      - "Build Image"
    types:
      - completed

jobs:
  deploy:
    name: Production deployment
    runs-on: ubuntu-latest
    steps:
    - uses: matootie/dokube@v1.3.4
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: k8s-main
    - name: Deployment rollout
      run: kubectl -n finances rollout restart deployments finances-easy-api