name: Deploy app
on:
  workflow_run:
    workflows:
      - "Build Jar"
    types:
      - completed

jobs:
  deploy:
    name: Production deployment
    runs-on: ubuntu-latest
    steps:
      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: jar
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: finances-easy-api
          environment_name: finances-easy-api
          version_label: finances-easy-api
          region: eu-west-1
          deployment_package: finances-easy-api.jar