name: Build Image
on:
  push:
    branches: [ main ]

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'
          architecture: x64
      - name: Run gradle build image
        run: ./gradlew bootBuildImage --imageName=alexandre3gomes/finances-easy-api
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Save docker image to a tarball
        run: docker save alexandre3gomes/finances-easy-api > finances-easy-api.tar
      - name: Archive docker image tarball
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: finances-easy-api.tar
  push_image:
    name: Push image to Dockerhub
    runs-on: ubuntu-latest
    needs:
      - build_image
    steps:
      - name: Download docker image tarball
        uses: actions/download-artifact@v2
        with:
          name: image
      - name: Load docker image tarball
        run: docker load < finances-easy-api.tar
      - name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Push image to registry
        run: docker push alexandre3gomes/finances-easy-api
