name: Build app
on:
  push:
    branches: [ main ]

jobs:
  Build_Image:
    runs-on: ubuntu-latest
    needs: [Tests]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'
          architecture: x64
      - name: Run gradle build image
        run: ./gradlew bootBuildImage --imageName=alexandre3gomes/finances-easy-api
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
  Login_Dockerhub:
    runs-on: ubuntu-latest
    needs: [ Tests ]
    steps:
      - name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  Push_Image_Dockerhub:
    runs-on: ubuntu-latest
    needs: [ Tests ]
    steps:
      - name: Push image to registry
        run: docker push alexandre3gomes/finances-easy-api
