name: Run tests
on:
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'
          architecture: x64
      - name: Run gradle klint
        run: ./gradlew ktlintFormat
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'
          architecture: x64
      - name: Run tests
        run: ./gradlew test